#!/bin/bash
#
# Author:       Paul Gear
# Copyright:	(c) 2010 Liberty Systems & Software <http://libertysys.com.au/>
# License:	GPLv3 <http://www.gnu.org/licenses/gpl.html>
# Description:  Run ntpmon in parallel for every host RRD
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.  
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.
#

if [ "$#" -gt 0 ]; then
    CMD="$1"
    shift
else
    CMD="dump"
fi
CGI_DIR=/usr/lib/cgi-bin
RRD_DIR=/var/lib/ntpmon
for i in $RRD_DIR/*.rrd; do
    host=`basename $i .rrd`
    $CGI_DIR/ntpmon $CMD $host "$@" &
    sleep 0.1
done
